export const UPDATE_THREAD_FIELD = 'UPDATE_THREAD_FIELD';
export const RESET_THREAD = 'RESET_THREAD';
export const SET_THREAD_DATA = 'SET_THREAD_DATA';
export const SET_SELECTED_THREAD = 'SET_SELECTED_THREAD';
export const SET_ALL_THREADS = 'SET_ALL_THREADS';